[general]
port = 3002

[platform]
discord = ""

[[nodes.a]]
me = false
domain = "http://localhost:3000"
disabled = true

[[nodes.b]]
me = false
domain = "http://localhost:3001"
disabled = false

[[nodes.c]]
me = true
domain = "http://localhost:3002"
disabled = false
